In [4]:
import numpy as np

In [2]:
a= np.zeros((5,5),dtype=int) #to get float valuse just remove np.array
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:
b = np.full((5,5),0) #for non-zero value replace 0 with any non-zero value
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [4]:
c = np.arange(10,101,5)
print(c)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [5]:
d = np.array([10,20,30,40,50,60])
print(d)

[10 20 30 40 50 60]


In [6]:
# to reshape the dimension of the array
d = np.array([10,20,30,40,50,60]).reshape(2,3)
print(d)
print(d.dtype)

[[10 20 30]
 [40 50 60]]
int32


In [12]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
print("Addition of two array is: ",n1 + n2)
print("Substraction of two array is: ",n1 - n2)
print("Multiplication of two array is: ",n1 * n2)
print("Division of two array is: ",n1 / n2)

Addition of two array is:  [5 7 9]
Substraction of two array is:  [-3 -3 -3]
Multiplication of two array is:  [ 4 10 18]
Division of two array is:  [0.25 0.4  0.5 ]


In [9]:
s = np.arange(10,91,10).reshape(3,3)
print(s)
print("3rd column from the numpy array is:\n",s[:,-1:])
print("2nd row from the numpy array is:\n",s[1:2,])
print("The intersection of first two rows and first two columns is:\n",s[0:2,0:2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
3rd column from the numpy array is:
 [[30]
 [60]
 [90]]
2nd row from the numpy array is:
 [[40 50 60]]
The intersection of first two rows and first two columns is:
 [[10 20]
 [40 50]]


s[rows,columns]

In [17]:
s[0:1,]

array([[10, 20, 30]])

In [19]:
s[0:1]

array([[10, 20, 30]])

In [20]:
s[:1]

array([[10, 20, 30]])

In [22]:
s[:,0:1]

array([[10],
       [40],
       [70]])

In [30]:
s[:,-1:]

array([[30],
       [60],
       [90]])

In [31]:
s[1:2,]

array([[40, 50, 60]])

In [37]:
s[-1:,-1:]

array([[90]])

In [38]:
s[2,2]

90

In [42]:
def fun(a,b,c):
    d=np.full((a,b),c)
    return d
a=int(input())
b=int(input())
c=int(input()) 
print(fun(a,b,c))

3
3
5
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [10]:
def math(a,b):
    sum1 = a+b
    return sum1

#a= int(input(np.array([])))
#b= int(input(np.array([])))
a=np.array([10,20,30])
b=np.array([40,50,60])
math(a,b)

array([50, 70, 90])

In [48]:
def math1(a):
    return a[:2,:2]
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The top-left matrix is: \n",math1(a))

array([[1, 2],
       [4, 5]])

In [12]:
def math1(a):
    return a[1:,1:]
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The bottom-right matrix is: \n",math1(a))

The top-left matrix is: 
 [[5 6]
 [8 9]]


In [51]:
def math2(a):
    b= np.mean(a)
    c=np.std(a)
    dict1={"mean":b,"std":c}
    return dict1


a = np.array([1,2,3])
math2(a)

{'mean': 2.0, 'std': 0.816496580927726}